project:
  type: website
  output-dir: docs

website:
  title: "eonbi's website for stat 244"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: stat_244_sc.qmd
        text: STAT244-SC

format:
  html:
    theme: vapor
    css: styles.css
    fontcolor: "#FFFFFF"
    toc: true

editor: visual

